import type { Booking } from "@/types/booking";
import type { Dress } from "@/types/dress";
import type { AdminNotification } from "@/types/notification";
import type { PlatformSettings } from "@/types/settings";
import type { Store } from "@/types/store";
import type { Subscription } from "@/types/subscription";
import type { Transaction } from "@/types/transaction";
import type { User } from "@/types/user";

const daysAgo = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
};

const daysFromNow = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString();
};

export const seedUsers: User[] = [
  {
    id: "user-customer-1",
    name: "Sara Benali",
    phone: "0555123456",
    email: "sara@diah.dz",
    role: "customer",
    status: "active",
    city: "الجزائر العاصمة",
    avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200",
    createdAt: daysAgo(90),
    ownedDressIds: [],
  },
  {
    id: "user-owner-1",
    name: "Amina Khaldi",
    phone: "0666789012",
    email: "amina@diah.dz",
    role: "individualOwner",
    status: "active",
    city: "الجزائر العاصمة",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200",
    createdAt: daysAgo(120),
    ownedDressIds: ["dress-3", "dress-5"],
  },
  {
    id: "user-store-1",
    name: "Fatima Zeroual",
    phone: "0777111222",
    email: "fatima@elegance.dz",
    role: "storeOwner",
    status: "active",
    city: "الجزائر العاصمة",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200",
    createdAt: daysAgo(200),
    ownedDressIds: ["dress-1", "dress-2", "dress-4", "dress-6", "dress-9", "dress-10"],
  },
  {
    id: "user-store-2",
    name: "Leila Messaoudi",
    phone: "0555987654",
    email: "leila@karakou.dz",
    role: "storeOwner",
    status: "active",
    city: "الجزائر العاصمة",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200",
    createdAt: daysAgo(150),
    ownedDressIds: ["dress-7", "dress-8"],
  },
  {
    id: "user-customer-2",
    name: "Yasmine Boudiaf",
    phone: "0555111222",
    email: "yasmine@mail.dz",
    role: "customer",
    status: "active",
    city: "وهران",
    createdAt: daysAgo(40),
    ownedDressIds: [],
  },
  {
    id: "user-customer-3",
    name: "Nour Haddad",
    phone: "0666333444",
    email: "nour@mail.dz",
    role: "customer",
    status: "suspended",
    city: "قسنطينة",
    createdAt: daysAgo(25),
    ownedDressIds: [],
  },
  {
    id: "user-owner-2",
    name: "Rania Cherif",
    phone: "0777000111",
    email: "rania@diah.dz",
    role: "individualOwner",
    status: "pending",
    city: "البليدة",
    createdAt: daysAgo(5),
    ownedDressIds: [],
  },
];

export const seedStores: Store[] = [
  {
    id: "store-1",
    name: "Maison Élégance",
    ownerId: "user-store-1",
    address: "8 شارع العربي بن مهيدي",
    city: "الجزائر العاصمة",
    category: "mixed",
    subscriptionId: "sub-1",
    status: "active",
    phone: "0777111222",
    logo: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=200",
    coverImage: "/dresses/wedding_dress.png",
    createdAt: daysAgo(200),
  },
  {
    id: "store-2",
    name: "Atelier Karakou",
    ownerId: "user-store-2",
    address: "22 شارع حسيبة بن بوعلي",
    city: "الجزائر العاصمة",
    category: "traditional",
    subscriptionId: "sub-2",
    status: "active",
    phone: "0555987654",
    logo: "/dresses/karakou.png",
    coverImage: "/dresses/karakou.png",
    createdAt: daysAgo(150),
  },
  {
    id: "store-3",
    name: "دار عرائس وهران",
    ownerId: "user-store-1",
    address: "الواجهة البحرية",
    city: "وهران",
    category: "wedding",
    status: "pending",
    phone: "041112233",
    createdAt: daysAgo(3),
  },
];

export const seedDresses: Dress[] = [
  {
    id: "dress-1",
    name: "فستان زفاف فاخر",
    description: "فستان زفاف دانتيل عاجي بذيل كاتدرائية.",
    images: ["/dresses/wedding_dress.png"],
    category: "Wedding",
    color: "عاجي",
    size: "M",
    price: 18000,
    deposit: 50000,
    status: "available",
    ownerId: "user-store-1",
    storeId: "store-1",
    rentalCount: 24,
    createdAt: daysAgo(180),
  },
  {
    id: "dress-2",
    name: "سهرة كحلية ليلية",
    description: "فستان سهرة ساتان بقصة انسيابية.",
    images: [
      "https://images.unsplash.com/photo-1568251188392-ae32f898cb3b?w=800&q=80",
      "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800&q=80",
    ],
    category: "Evening",
    color: "كحلي",
    size: "S",
    price: 8000,
    deposit: 25000,
    status: "available",
    ownerId: "user-store-1",
    storeId: "store-1",
    rentalCount: 18,
    createdAt: daysAgo(160),
  },
  {
    id: "dress-3",
    name: "قفطان أخضر زمردي",
    description: "قفطان تقليدي بتطريز ذهبي.",
    images: [
      "https://images.unsplash.com/photo-1765229280390-e05fb240aed8?w=800&q=80",
      "https://images.unsplash.com/photo-1765229276545-c23adb5442bf?w=800&q=80",
    ],
    category: "Caftan",
    color: "زمردي",
    size: "L",
    price: 8500,
    deposit: 20000,
    status: "available",
    ownerId: "user-owner-1",
    rentalCount: 12,
    createdAt: daysAgo(100),
  },
  {
    id: "dress-4",
    name: "فستان مخملي بورغندي",
    description: "فستان مخملي غني لحفلات الخطوبة.",
    images: [
      "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=800&q=80",
      "https://images.unsplash.com/photo-1568252542512-9fe8fe9c87bb?w=800&q=80",
    ],
    category: "Evening",
    color: "بورغندي",
    size: "M",
    price: 7500,
    deposit: 20000,
    status: "available",
    ownerId: "user-store-1",
    storeId: "store-1",
    rentalCount: 15,
    createdAt: daysAgo(90),
  },
  {
    id: "dress-5",
    name: "كاراكو جزائري أصيل",
    description: "كاراكو أصيل بتطريز فتلة ذهبية وفضية.",
    images: ["/dresses/karakou.png"],
    category: "Karakou",
    color: "أسود وذهبي",
    size: "M",
    price: 15000,
    deposit: 40000,
    status: "available",
    ownerId: "user-owner-1",
    rentalCount: 8,
    createdAt: daysAgo(80),
  },
  {
    id: "dress-6",
    name: "فستان عروس وردي لؤلؤي",
    description: "فستان عروس وردي ناعم بتفاصيل لؤلؤية.",
    images: ["/dresses/wedding_dress.png"],
    category: "Wedding",
    color: "وردي",
    size: "S",
    price: 16000,
    deposit: 45000,
    status: "pending",
    ownerId: "user-store-1",
    storeId: "store-1",
    rentalCount: 0,
    createdAt: daysAgo(2),
  },
  {
    id: "dress-7",
    name: "قفطان أزرق ملكي",
    description: "قفطان مميز للمناسبات التقليدية.",
    images: [
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80",
      "https://images.unsplash.com/photo-1547697933-66bcb20f114a?w=800&q=80",
    ],
    category: "Caftan",
    color: "أزرق ملكي",
    size: "XL",
    price: 12000,
    deposit: 30000,
    status: "available",
    ownerId: "user-store-2",
    storeId: "store-2",
    rentalCount: 10,
    createdAt: daysAgo(70),
  },
  {
    id: "dress-8",
    name: "فستان سهرة ذهبي",
    description: "فستان سهرة ذهبي للمناسبات الكبرى.",
    images: [
      "https://images.unsplash.com/photo-1769883204270-909b63437a30?w=800&q=80",
      "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800&q=80",
    ],
    category: "Evening",
    color: "ذهبي",
    size: "M",
    price: 9500,
    deposit: 28000,
    status: "hidden",
    ownerId: "user-store-2",
    storeId: "store-2",
    rentalCount: 6,
    createdAt: daysAgo(60),
  },
  {
    id: "dress-9",
    name: "حقيبة يد متعددة الجيوب",
    description: "حقيبة يد بنية متعددة الجيوب للمساء والنهار.",
    images: ["/dresses/accessory_purse_1.png"],
    category: "Accessories",
    color: "بني",
    size: "مقاس واحد",
    price: 600,
    deposit: 3000,
    status: "available",
    ownerId: "user-store-1",
    storeId: "store-1",
    rentalCount: 30,
    createdAt: daysAgo(40),
  },
  {
    id: "dress-10",
    name: "حقيبة كتف بنية كلاسيكية",
    description: "حقيبة كتف بنية أنيقة بتفاصيل ذهبية.",
    images: ["/dresses/accessory_purse_2.png"],
    category: "Accessories",
    color: "بني",
    size: "مقاس واحد",
    price: 700,
    deposit: 4000,
    status: "available",
    ownerId: "user-store-1",
    storeId: "store-1",
    rentalCount: 22,
    createdAt: daysAgo(35),
  },
];

export const seedBookings: Booking[] = [
  {
    id: "booking-1",
    customerId: "user-customer-1",
    dressId: "dress-2",
    storeId: "store-1",
    startDate: daysFromNow(14).slice(0, 10),
    endDate: daysFromNow(16).slice(0, 10),
    price: 24000,
    deposit: 25000,
    status: "approved",
    createdAt: daysAgo(2),
  },
  {
    id: "booking-2",
    customerId: "user-customer-1",
    dressId: "dress-5",
    startDate: daysFromNow(21).slice(0, 10),
    endDate: daysFromNow(23).slice(0, 10),
    price: 18000,
    deposit: 20000,
    status: "pending",
    createdAt: daysAgo(0),
  },
  {
    id: "booking-3",
    customerId: "user-customer-2",
    dressId: "dress-1",
    storeId: "store-1",
    startDate: daysAgo(20).slice(0, 10),
    endDate: daysAgo(18).slice(0, 10),
    price: 36000,
    deposit: 50000,
    status: "completed",
    createdAt: daysAgo(30),
  },
  {
    id: "booking-4",
    customerId: "user-customer-2",
    dressId: "dress-7",
    storeId: "store-2",
    startDate: daysAgo(10).slice(0, 10),
    endDate: daysAgo(8).slice(0, 10),
    price: 24000,
    deposit: 30000,
    status: "returned",
    createdAt: daysAgo(15),
  },
  {
    id: "booking-5",
    customerId: "user-customer-3",
    dressId: "dress-4",
    storeId: "store-1",
    startDate: daysAgo(5).slice(0, 10),
    endDate: daysAgo(3).slice(0, 10),
    price: 15000,
    deposit: 20000,
    status: "cancelled",
    createdAt: daysAgo(8),
  },
];

export const seedTransactions: Transaction[] = [
  {
    id: "tx-1",
    bookingId: "booking-1",
    customerId: "user-customer-1",
    amount: 25000,
    type: "deposit",
    status: "completed",
    date: daysAgo(2),
    description: "تأمين — سهرة كحلية ليلية",
  },
  {
    id: "tx-2",
    bookingId: "booking-1",
    customerId: "user-customer-1",
    amount: 24000,
    type: "rental",
    status: "pending",
    date: daysAgo(2),
    description: "دفعة إيجار — سهرة كحلية ليلية",
  },
  {
    id: "tx-3",
    bookingId: "booking-3",
    customerId: "user-customer-2",
    storeId: "store-1",
    amount: 36000,
    type: "rental",
    status: "completed",
    date: daysAgo(30),
    description: "إيجار — فستان زفاف فاخر",
  },
  {
    id: "tx-4",
    bookingId: "booking-3",
    storeId: "store-1",
    amount: 3600,
    type: "commission",
    status: "completed",
    date: daysAgo(29),
    description: "عمولة المنصة 10%",
  },
  {
    id: "tx-5",
    storeId: "store-1",
    amount: 9000,
    type: "subscription",
    status: "completed",
    date: daysAgo(20),
    description: "اشتراك شهري — ميزون إليغانس",
  },
  {
    id: "tx-6",
    bookingId: "booking-5",
    customerId: "user-customer-3",
    amount: 20000,
    type: "refund",
    status: "refunded",
    date: daysAgo(7),
    description: "استرجاع — حجز ملغى",
  },
];

export const seedSubscriptions: Subscription[] = [
  {
    id: "sub-1",
    storeId: "store-1",
    plan: "monthly",
    price: 9000,
    startDate: daysAgo(20).slice(0, 10),
    endDate: daysFromNow(10).slice(0, 10),
    status: "active",
  },
  {
    id: "sub-2",
    storeId: "store-2",
    plan: "yearly",
    price: 90000,
    startDate: daysAgo(100).slice(0, 10),
    endDate: daysFromNow(265).slice(0, 10),
    status: "active",
  },
  {
    id: "sub-3",
    storeId: "store-3",
    plan: "trial",
    price: 0,
    startDate: daysAgo(3).slice(0, 10),
    endDate: daysFromNow(27).slice(0, 10),
    status: "trial",
  },
];

export const seedNotifications: AdminNotification[] = [
  {
    id: "notif-1",
    title: "مرحباً بك في دِياه",
    message: "اكتشفي فساتين فاخرة لكل مناسبة.",
    target: "all",
    createdAt: daysAgo(10),
  },
  {
    id: "notif-2",
    title: "محل جديد بانتظار الموافقة",
    message: "محل عرائس وهران بانتظار المراجعة.",
    target: "stores",
    createdAt: daysAgo(3),
  },
  {
    id: "notif-3",
    title: "تشكيلة رمضان",
    message: "أبرزي القفاطين التقليدية هذا الموسم.",
    target: "customers",
    createdAt: daysAgo(1),
  },
];

export const seedSettings: PlatformSettings = {
  categories: ["Wedding", "Evening", "Traditional", "Karakou", "Caftan", "Accessories"],
  dressTypes: ["فستان طويل", "قفطان", "كاراكو", "كوكتيل", "إكسسوار"],
  commissionPercent: 10,
  defaultDepositPercent: 40,
  currency: "DZD",
  supportEmail: "support@diah.dz",
  notifyNewUsers: true,
  notifyNewStores: true,
  notifyPendingDresses: true,
};

/** Monthly series for charts (last 6 months). */
export const seedMonthlyStats = [
  { month: "مارس", revenue: 420000, bookings: 28, users: 40 },
  { month: "أبريل", revenue: 510000, bookings: 34, users: 55 },
  { month: "مايو", revenue: 480000, bookings: 31, users: 68 },
  { month: "يونيو", revenue: 620000, bookings: 42, users: 82 },
  { month: "يوليو", revenue: 710000, bookings: 49, users: 96 },
  { month: "أغسطس", revenue: 580000, bookings: 38, users: 110 },
];
