import type { Booking } from "@/types/booking";
import type { Dress } from "@/types/dress";
import type { AdminNotification } from "@/types/notification";
import type { PlatformSettings } from "@/types/settings";
import type { Store } from "@/types/store";
import type { Subscription } from "@/types/subscription";
import type { Transaction } from "@/types/transaction";
import type { User } from "@/types/user";

const daysAgo = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
};

const daysFromNow = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString();
};

export const seedUsers: User[] = [
  {
    id: "user-customer-1",
    name: "Sara Benali",
    phone: "0555123456",
    email: "sara@diah.dz",
    role: "customer",
    status: "active",
    city: "Algiers",
    avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200",
    createdAt: daysAgo(90),
    ownedDressIds: [],
  },
  {
    id: "user-owner-1",
    name: "Amina Khaldi",
    phone: "0666789012",
    email: "amina@diah.dz",
    role: "individualOwner",
    status: "active",
    city: "Algiers",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200",
    createdAt: daysAgo(120),
    ownedDressIds: ["dress-3", "dress-5"],
  },
  {
    id: "user-store-1",
    name: "Fatima Zeroual",
    phone: "0777111222",
    email: "fatima@elegance.dz",
    role: "storeOwner",
    status: "active",
    city: "Algiers",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200",
    createdAt: daysAgo(200),
    ownedDressIds: ["dress-1", "dress-2", "dress-4", "dress-6"],
  },
  {
    id: "user-store-2",
    name: "Leila Messaoudi",
    phone: "0555987654",
    email: "leila@karakou.dz",
    role: "storeOwner",
    status: "active",
    city: "Algiers",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200",
    createdAt: daysAgo(150),
    ownedDressIds: ["dress-7", "dress-8"],
  },
  {
    id: "user-customer-2",
    name: "Yasmine Boudiaf",
    phone: "0555111222",
    email: "yasmine@mail.dz",
    role: "customer",
    status: "active",
    city: "Oran",
    createdAt: daysAgo(40),
    ownedDressIds: [],
  },
  {
    id: "user-customer-3",
    name: "Nour Haddad",
    phone: "0666333444",
    email: "nour@mail.dz",
    role: "customer",
    status: "suspended",
    city: "Constantine",
    createdAt: daysAgo(25),
    ownedDressIds: [],
  },
  {
    id: "user-owner-2",
    name: "Rania Cherif",
    phone: "0777000111",
    email: "rania@diah.dz",
    role: "individualOwner",
    status: "pending",
    city: "Blida",
    createdAt: daysAgo(5),
    ownedDressIds: ["dress-9"],
  },
];

export const seedStores: Store[] = [
  {
    id: "store-1",
    name: "Maison Élégance",
    ownerId: "user-store-1",
    address: "8 Rue Larbi Ben M'hidi",
    city: "Algiers",
    category: "mixed",
    subscriptionId: "sub-1",
    status: "active",
    phone: "0777111222",
    logo: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=200",
    coverImage: "https://images.unsplash.com/photo-1519741497674-611481863552?w=800",
    createdAt: daysAgo(200),
  },
  {
    id: "store-2",
    name: "Atelier Karakou",
    ownerId: "user-store-2",
    address: "22 Rue Hassiba Ben Bouali",
    city: "Algiers",
    category: "traditional",
    subscriptionId: "sub-2",
    status: "active",
    phone: "0555987654",
    logo: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=200",
    coverImage: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800",
    createdAt: daysAgo(150),
  },
  {
    id: "store-3",
    name: "Oran Bridal House",
    ownerId: "user-store-1",
    address: "Front de Mer",
    city: "Oran",
    category: "wedding",
    status: "pending",
    phone: "041112233",
    createdAt: daysAgo(3),
  },
];

export const seedDresses: Dress[] = [
  {
    id: "dress-1",
    name: "Luxury Wedding Gown",
    description: "Ivory lace wedding gown with cathedral train.",
    images: ["https://images.unsplash.com/photo-1594552072239-b1f8c8d51e54?w=600"],
    category: "Wedding",
    color: "Ivory",
    size: "M",
    price: 18000,
    deposit: 50000,
    status: "available",
    ownerId: "user-store-1",
    storeId: "store-1",
    rentalCount: 24,
    createdAt: daysAgo(180),
  },
  {
    id: "dress-2",
    name: "Midnight Navy Soirée",
    description: "Satin evening dress with delicate draping.",
    images: ["https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600"],
    category: "Evening",
    color: "Navy",
    size: "S",
    price: 8000,
    deposit: 25000,
    status: "available",
    ownerId: "user-store-1",
    storeId: "store-1",
    rentalCount: 18,
    createdAt: daysAgo(160),
  },
  {
    id: "dress-3",
    name: "Emerald Green Caftan",
    description: "Traditional caftan with gold embroidery.",
    images: ["https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600"],
    category: "Caftan",
    color: "Emerald",
    size: "L",
    price: 8500,
    deposit: 20000,
    status: "available",
    ownerId: "user-owner-1",
    rentalCount: 12,
    createdAt: daysAgo(100),
  },
  {
    id: "dress-4",
    name: "Burgundy Velvet Dress",
    description: "Rich velvet gown for engagement nights.",
    images: ["https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600"],
    category: "Evening",
    color: "Burgundy",
    size: "M",
    price: 7500,
    deposit: 20000,
    status: "available",
    ownerId: "user-store-1",
    storeId: "store-1",
    rentalCount: 15,
    createdAt: daysAgo(90),
  },
  {
    id: "dress-5",
    name: "Traditional Algerian Karakou",
    description: "Authentic karakou with gold and silver fetla.",
    images: ["https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600"],
    category: "Karakou",
    color: "Black & Gold",
    size: "M",
    price: 15000,
    deposit: 40000,
    status: "available",
    ownerId: "user-owner-1",
    rentalCount: 8,
    createdAt: daysAgo(80),
  },
  {
    id: "dress-6",
    name: "Pearl Blush Bridal",
    description: "Soft blush bridal dress with pearl details.",
    images: ["https://images.unsplash.com/photo-1515372039744-b8f0229a06a2?w=600"],
    category: "Wedding",
    color: "Blush",
    size: "S",
    price: 16000,
    deposit: 45000,
    status: "pending",
    ownerId: "user-store-1",
    storeId: "store-1",
    rentalCount: 0,
    createdAt: daysAgo(2),
  },
  {
    id: "dress-7",
    name: "Royal Blue Caftan",
    description: "Statement caftan for ceremonies.",
    images: ["https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=600"],
    category: "Caftan",
    color: "Royal Blue",
    size: "XL",
    price: 12000,
    deposit: 30000,
    status: "available",
    ownerId: "user-store-2",
    storeId: "store-2",
    rentalCount: 10,
    createdAt: daysAgo(70),
  },
  {
    id: "dress-8",
    name: "Golden Evening Gown",
    description: "Metallic gold gown for galas.",
    images: ["https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=600"],
    category: "Evening",
    color: "Gold",
    size: "M",
    price: 9500,
    deposit: 28000,
    status: "hidden",
    ownerId: "user-store-2",
    storeId: "store-2",
    rentalCount: 6,
    createdAt: daysAgo(60),
  },
  {
    id: "dress-9",
    name: "Rose Engagement Dress",
    description: "Awaiting platform review.",
    images: ["https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=600"],
    category: "Evening",
    color: "Rose",
    size: "S",
    price: 7000,
    deposit: 18000,
    status: "pending",
    ownerId: "user-owner-2",
    rentalCount: 0,
    createdAt: daysAgo(1),
  },
];

export const seedBookings: Booking[] = [
  {
    id: "booking-1",
    customerId: "user-customer-1",
    dressId: "dress-2",
    storeId: "store-1",
    startDate: daysFromNow(14).slice(0, 10),
    endDate: daysFromNow(16).slice(0, 10),
    price: 24000,
    deposit: 25000,
    status: "approved",
    createdAt: daysAgo(2),
  },
  {
    id: "booking-2",
    customerId: "user-customer-1",
    dressId: "dress-5",
    startDate: daysFromNow(21).slice(0, 10),
    endDate: daysFromNow(23).slice(0, 10),
    price: 18000,
    deposit: 20000,
    status: "pending",
    createdAt: daysAgo(0),
  },
  {
    id: "booking-3",
    customerId: "user-customer-2",
    dressId: "dress-1",
    storeId: "store-1",
    startDate: daysAgo(20).slice(0, 10),
    endDate: daysAgo(18).slice(0, 10),
    price: 36000,
    deposit: 50000,
    status: "completed",
    createdAt: daysAgo(30),
  },
  {
    id: "booking-4",
    customerId: "user-customer-2",
    dressId: "dress-7",
    storeId: "store-2",
    startDate: daysAgo(10).slice(0, 10),
    endDate: daysAgo(8).slice(0, 10),
    price: 24000,
    deposit: 30000,
    status: "returned",
    createdAt: daysAgo(15),
  },
  {
    id: "booking-5",
    customerId: "user-customer-3",
    dressId: "dress-4",
    storeId: "store-1",
    startDate: daysAgo(5).slice(0, 10),
    endDate: daysAgo(3).slice(0, 10),
    price: 15000,
    deposit: 20000,
    status: "cancelled",
    createdAt: daysAgo(8),
  },
];

export const seedTransactions: Transaction[] = [
  {
    id: "tx-1",
    bookingId: "booking-1",
    customerId: "user-customer-1",
    amount: 25000,
    type: "deposit",
    status: "completed",
    date: daysAgo(2),
    description: "Deposit — Midnight Navy Soirée",
  },
  {
    id: "tx-2",
    bookingId: "booking-1",
    customerId: "user-customer-1",
    amount: 24000,
    type: "rental",
    status: "pending",
    date: daysAgo(2),
    description: "Rental payment — Midnight Navy Soirée",
  },
  {
    id: "tx-3",
    bookingId: "booking-3",
    customerId: "user-customer-2",
    storeId: "store-1",
    amount: 36000,
    type: "rental",
    status: "completed",
    date: daysAgo(30),
    description: "Rental — Luxury Wedding Gown",
  },
  {
    id: "tx-4",
    bookingId: "booking-3",
    storeId: "store-1",
    amount: 3600,
    type: "commission",
    status: "completed",
    date: daysAgo(29),
    description: "Platform commission 10%",
  },
  {
    id: "tx-5",
    storeId: "store-1",
    amount: 9000,
    type: "subscription",
    status: "completed",
    date: daysAgo(20),
    description: "Monthly subscription — Maison Élégance",
  },
  {
    id: "tx-6",
    bookingId: "booking-5",
    customerId: "user-customer-3",
    amount: 20000,
    type: "refund",
    status: "refunded",
    date: daysAgo(7),
    description: "Refund — cancelled booking",
  },
];

export const seedSubscriptions: Subscription[] = [
  {
    id: "sub-1",
    storeId: "store-1",
    plan: "monthly",
    price: 9000,
    startDate: daysAgo(20).slice(0, 10),
    endDate: daysFromNow(10).slice(0, 10),
    status: "active",
  },
  {
    id: "sub-2",
    storeId: "store-2",
    plan: "yearly",
    price: 90000,
    startDate: daysAgo(100).slice(0, 10),
    endDate: daysFromNow(265).slice(0, 10),
    status: "active",
  },
  {
    id: "sub-3",
    storeId: "store-3",
    plan: "trial",
    price: 0,
    startDate: daysAgo(3).slice(0, 10),
    endDate: daysFromNow(27).slice(0, 10),
    status: "trial",
  },
];

export const seedNotifications: AdminNotification[] = [
  {
    id: "notif-1",
    title: "Welcome to Diah",
    message: "Discover luxury dresses for every occasion.",
    target: "all",
    createdAt: daysAgo(10),
  },
  {
    id: "notif-2",
    title: "New store pending approval",
    message: "Oran Bridal House awaits review.",
    target: "stores",
    createdAt: daysAgo(3),
  },
  {
    id: "notif-3",
    title: "Ramadan collection",
    message: "Feature traditional caftans this season.",
    target: "customers",
    createdAt: daysAgo(1),
  },
];

export const seedSettings: PlatformSettings = {
  categories: ["Wedding", "Evening", "Traditional", "Karakou", "Caftan", "Accessories"],
  dressTypes: ["Gown", "Caftan", "Karakou", "Cocktail", "Accessory"],
  commissionPercent: 10,
  defaultDepositPercent: 40,
  currency: "DZD",
  supportEmail: "support@diah.dz",
  notifyNewUsers: true,
  notifyNewStores: true,
  notifyPendingDresses: true,
};

/** Monthly series for charts (last 6 months). */
export const seedMonthlyStats = [
  { month: "Mar", revenue: 420000, bookings: 28, users: 40 },
  { month: "Apr", revenue: 510000, bookings: 34, users: 55 },
  { month: "May", revenue: 480000, bookings: 31, users: 68 },
  { month: "Jun", revenue: 620000, bookings: 42, users: 82 },
  { month: "Jul", revenue: 710000, bookings: 49, users: 96 },
  { month: "Aug", revenue: 580000, bookings: 38, users: 110 },
];
